server.port: 8000
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false
spring.applicationx.name: eureka
eureka.client.service-url.defaultZone: http://localhost:${server.port}/eureka/